name: Homepod App Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/homepodapp:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/homepodapp:${{ github.sha }}      

      #- name: 'Deploy to Azure Container Instances'
      #  uses: 'azure/aci-deploy@v1'
      #  with:
      #    resource-group: ${{ secrets.RESOURCE_GROUP }}
      #    dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
      #    image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/homepodapp:${{ github.sha }}
      #    registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      #    registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #    registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #    name: homepodapp
      #    location: 'north europe'

      - name: logout
        run: |
          az logout