name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production

    permissions:
      contents: read
      packages: write  # Required to push to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/homepod:latest .
          docker tag ghcr.io/${{ github.repository_owner }}/homepod:latest ghcr.io/${{ github.repository_owner }}/homepod:${{ github.sha }}

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/homepod:latest
          docker push ghcr.io/${{ github.repository_owner }}/homepod:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Deploy to SSH Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/homepod:latest
            docker stop homepod-box || true && docker rm homepod-box || true
            docker run -d --name homepod-box -p 3000:3000 \
              -e GA_TRACKING_ID=${{ vars.GA_TRACKING_ID }} \
              -e VITE_HOMEPOD_BASE_URL=${{ vars.VITE_HOMEPOD_BASE_URL }} \
              -e VITE_MAX_CHARACTER_COUNT=${{ vars.VITE_MAX_CHARACTER_COUNT }} \
              -e VITE_STORIPOD_BASE_URL=${{ vars.VITE_STORIPOD_BASE_URL }} \
              --restart unless-stopped ghcr.io/${{ github.repository_owner }}/homepod:latest
            docker image prune -a -f